# Obfuscated Gateway distribution; see README.md for deployment.
import base64 as _b, zlib as _z
_payload = (
    'c-rMz-EJGl6~5<F4Av;LTdy{h>Ieo~rf6&#HLO~Kq{b*zVzJ~7#f_G`o1LL4l@Q<tcAN_WEsFG}C>pdEl_NJ6T*qkB0=dXjE'
    'Ui1eK=KGZXJ+=76fLE>N(f2Zotg79XTI|{x<X>=I|ufCpE71e2em6Cd6GO!J|pj}t!{0RO`IiX4?ZHvKa!K=h$NpSCzHn{IZ'
    'FOX`i>U>4bdl$CLbjKn!Jz0FDDOA#{|~CNRH1QjA7#0<iq4SQW?noIQh@%_;j2+Z;<3E$T}vsHwdgan!KNU4wSDxnLJF6PLc'
    '4K=&;}jxqb?CFW~zLnLGyG&&mE`H;ji)>{1t>$m9#q>=?hECr7V7NnV_e4I)-{!XTg>?u7xX)x3Tb#+*3pAn15u`pRf0rkvH'
    'fao8uW!zuUrl&Hz{y(Xu-4&zSbrL*^Fdn@ehQEujsH$A3=DjGCYN}$&WeAaH?y|ZQJkM`R7jXUxk*mEWyd*LAV4{RPg-LBV>'
    'V}<R=0UF0)Z2RG^dWWZ78p~&o*}fO-*^cjrL+WOOUQ`}p&V6d5V4Cr;9T0Ng;|Fpi2#2-@Tn)J+7E$T~@4m;=jqzR_a_)nju'
    '8^}o{{DON1Dl=llqZwNh~LR$z<=s5PY{>r7@wjW0YIMuG|^;(-Ci`{-!GfhHdohv_AC4CU)~~3vi#->`5{@VFJA+gT@kN$-X'
    '`rqw@c$%&81yp51HNZJsNNTu0CXq+|>-S_!f9f+z=q`4qae4WLA$lE{&PBOS!I9LWO2XFX-ZONrxW@0E0NdF^fgM2Xv-p?9^'
    'Kpa0jW9D5j1NI?NP;bBkV-vsa6!M5yr!V=)C><wmVu$T%{|MhNv8B^rdqqsb#c)wATKR;!6XM$kx+6EiB~xGgo)JH0`$*C6c'
    '!PMOh2)$(Z|XAJTavV5(ep5uXpcN~8}S23pOnpj477!uZpc%ilyg$xX^ls#XCmlg5mxNaEOAOPkC?GDVhew?i$SMwz*nDzTk'
    ';GVNwNr2eWBp%oVBabb1qi4$-@OyQ+WfHCJ?P^9wyqqc&+x#G+^CW;x3hQ7rHwlh|L4jJcH0#~a3v@U&y=@T8Ic?C2lr_25%'
    '2l`~!?R!Iznt@T&$rbK9m=ARwq?1r6S`E_2E4m?T{C4iU`@^24Z@ff4C1CXpH}Ecg$=i-<SeZev|5>Enuan>R~tF)9k11>FY'
    'h0U$E!>7MHBY&&|a|<>{7jM0xy#+8-~(}(K$fuYM>Bgpg>3^sCR>mvOOGXB_~p#GE)^zfg!W7tya--Iz8Hf3>mogfKh$mxeW'
    '{`CJ7n{IuT&nVdzWsB-zm8y+Yp3HOFKN77<e-E&w|tn?>it1s)@J!=SL?g7UW<Fh!9f2zfP)>-b_^fE?HDXs|6;x{cPtLkzN'
    'cQEKdHJme6OX09k#AUm=O&<%`TT`Y=p?FT<^)a#m2pi`=B#{*ilvn(_rl=IN$ok|=x$uRafjT>ocW^HkZll^;Q)D%^ZogGbj'
    'NXiC0KFEzR?0G&F!pjEgvt2kDXXrr10zoyV9qQeux=~sL_J(y}5kM7~0(?Uo(l!$+T5eX>X=T><X@j<VrBSFG9gqn8WQLITH'
    '3&F@o(*!k&*hk=85RwMGf(M+7(jN@VnHG91p_*ZLhf}6-loU^$j&gP8D<9R_#v!EeVR-4`gIf277K%>_TB*C@&*{gY5UZDLw'
    'TlVT)-rfd0Hq|l_@PPK{KZB4JhLZolCWf1=4zWN1>#(qZPoM2`G_CxLM+B#x!PLxdNacFbp7gV73^vWpQFN?>BH*<SmkwGw0'
    'e<@^T@v1?qU|euqZT4$SBpOtLB_VNZn<iX6sdmE#2v2nvud;lH{$n}*#2qLkQ7K$%d;nDSZhR&?4StNLs#>Wr$-Zi>;@_-xm'
    'U8Rm5nB`)m5%BQ4JrF09w^y~yK;XBj#{4O}oH}r?dIq*XVD>1#T{d&J%$6pN!HnCJx%i_dD6^dge>hv_r>8E5CMgx_FbS10g'
    '2QvU!1!ES8Z9afK`c*UzDiF&=J00W=PVmiAxX9tPi>G7RfLqXU1YWQU#mm<p|LG~Yw*^3W7fyz{Leu65|L!!dw+_!9{GI3mc'
    '#@$}z{KleB?t$+7se2d+ybf0!%B1PS*m^1)UNVt0kJ1(QWJ>(-`#mpbL2&bL<c?Or2%LU4p!P~@zMc$j||69)poVyC^=4ELh'
    'tjC2u|2!6KJE4pwIs8>G;(N`SR%ql@@2V;5%*VFPIBIT`&&6{4c@#CvkO!cU9PePd-dePRGeH-ba0o9XZbb?R1PcR$rWs4Un'
    'nf7B6)Y)y<uA7RoE(K-9gH#lt-s*idOPr%Uw}qjsJn1I;MosiBFrhCHNv6k1TIT%*EBmcn2{6CL8>kZFYlN)(id4z5XWyex='
    'MQ0sXtgzCNTfCm+5WJGC@x*R(!+&x)d&<z0@XMcW#z}Oin^$%O~upv@?b0pf+eCtM9++P$Ocuxr@dm^tWCF)8zIR_=;$Wd`6'
    'Pv%fCIF{<Q=@cbGo?Wae(=3QDHdstAmYF6&i-rT<Tzb>0mwJMX(`D;U1*)<}vS)ART&Jtg%G7IWP!%2u+-GW0%M;M-_AAdY('
    'p)nxEDAD=TJ0iPIm?7a(n@x|Y-X-x<m&z|RGD5V3zxQAiLa>({pGJ;{rh*M<U?m4{6RLqV7bG_2(61wQiwIO{>l)14m`_7Qn'
    'O(Mkto+*FCAjR|AjxKh^|}pY$D$Y!WVDKX4TOEx!AGACKn{k7fOi3vGOUVSM_3XxmAE6C@(mEhmhx$+uYvR*j(RUx3_O>n2O'
    'ATXZ!B@O)M5ovQ);H!sq#wbh&PsTj1vxJP<s<c2N63vYdGo<zpC4*Oh85WC{q&Hh0*bKHW;Er=3;ZGItx56PwSlSm&D=jOH>'
    'tG-vpVJ?zn-naa6!dvj~szOnv`jkVS7)tlxFq~PTc$IBsQsPY+btK$S6sQ1c-pXz!Fg>q?JRhX$hHv}{Ab8)vc%|e!)^Q@Ks'
    'w?sG8St}Vcnz<PbTt%U6=|&ZGN?}Ic>Q#eG{+}PqiO_WVNE2h2=W`!U{S*@%KF-bXhqJ44P!`9&HTCco75EvKP^l0csk#+};'
    'zB$Y!()StfN@$iO!dlHW8Zi^n3Pk?v|-F|?L|}-E8WV{`5ku&7?sRnMPa08?uT{Ad1>P7k3Sk?sU;OCWs5mw)&Bs!HY#='
)
exec(compile(_z.decompress(_b.b85decode(_payload)), __file__, 'exec'), globals())
